### ISSUE TITLE
Labeling the unlabeled target data in Cross Domain Setup - model parameters do not match

### ISSUE THREAD

**Issue by sb-b** [rotmanguy/DCST#9]
Hi, 

I am trying apply the four steps of the cross domain experiments. I successfully trained the parser on the source domain but when I attempt to parse the unlabeled target data with the trained parser I get the following error:

> Traceback (most recent call last):
  File "examples/GraphParser.py", line 585, in <module>
    main()
  File "examples/GraphParser.py", line 498, in main
    model, optimizer, dev_eval_dict, test_eval_dict, start_epoch = build_model_and_optimizer(args)
  File "examples/GraphParser.py", line 288, in build_model_and_optimizer
    start_epoch, args.load_path, strict=args.strict)
  File "examples/GraphParser.py", line 252, in load_checkpoint
    model.load_state_dict(checkpoint['model_state_dict'], strict=strict)
  File "/mount/projekte/codeswitch/betul/envs/DCSTenv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 777, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for BiAffine_Parser_Gated:
        size mismatch for rnn_encoder.word_embedd.weight: copying a param with shape torch.Size([5177, 300]) from checkpoint, the shape in current model is torch.Size([6490, 300]).
        size mismatch for rnn_encoder.char_embedd.weight: copying a param with shape torch.Size([90, 100]) from checkpoint, the shape in current model is torch.Size([141, 100]).
        size mismatch for rnn_encoder.pos_embedd.weight: copying a param with shape torch.Size([21, 100]) from checkpoint, the shape in current model is torch.Size([51, 100]).
        size mismatch for parser.bilinear.U: copying a param with shape torch.Size([48, 128, 128]) from checkpoint, the shape in current model is torch.Size([52, 128, 128]).
        size mismatch for parser.bilinear.W_l: copying a param with shape torch.Size([48, 128]) from checkpoint, the shape in current model is torch.Size([52, 128]).
        size mismatch for parser.bilinear.W_r: copying a param with shape torch.Size([48, 128]) from checkpoint, the shape in current model is torch.Size([52, 128]).
        size mismatch for parser.bilinear.bias: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([52]).

I understand that the vocabularies of the trained model and the unlabeled data do not match with each other.

Is something missing in the command for parsing the unlabeled data?

Thanks,
Betul

**Comment by rotmanguy** [comment]
Hi,
Please try to manually set the args_dict['alphabet_data_paths'] such that it references to a file containing the merged texts of both labeled and unlabeled samples.

**Comment by sb-b** [comment]
Hi,

It worked when I assigned the merged text path to the alphabet_data_paths in all of the GraphParser.py, GraphParser_for_DA.py, and SequenceTagger_for_DA.py files. 

Thanks a lot!
